chili/src/main/java/com/design2/chili2/view/cells/BaseCellView.kt
chili/src/main/res/values/attrs.xml

Добивил аттрибудт в BaseCellView для добавления background через xml.

adding cellBackground attribute in BaseCellView.kt

---

chili/src/main/java/com/design2/chili2/view/cells/EndIconCellView.kt

https://jira.devcats.kg/browse/OMD-10706

OMD-10706_hide_end_icon_on_shimmering

---

chili/src/main/res-screen/cells_views/layout/chili_view_cell_base.xml

Забыл убрать тестовое значение 72dp

after review [3]

---

app/src/main/java/com/design2/app/fragments/BottomSheetsFragment.kt
chili/src/main/java/com/design2/chili2/view/modals/base/BaseViewBottomSheetDialogFragment.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/ActionBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/DescriptionBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/DetailedInfoBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/InfoBottomSheet.kt
chili/src/main/res-screen/modals/layout/chili_view_bottom_sheet_base.xml
chili/src/main/res-screen/modals/layout/chili_view_bottom_sheet_description.xml
chili/src/main/res-screen/modals/layout/chili_view_bottom_sheet_detailed_info.xml
chili/src/main/res-screen/modals/layout/chili_view_bottom_sheet_info.xml

Убрал в DescriptionBottomSheet, DetailedInfoBottomSheet и InfoBottomSheet общий padding в 16 dp который был в коде.
Также удалил реализацию closeIcon из BaseViewBottomSheetDialogFragment и сделал для этих BS свои closeIcon.

bottomSheet padding and closeIcon fix

---

chili/src/main/java/com/design2/chili2/view/buttons/IconedButton.kt
chili/src/main/java/com/design2/chili2/view/buttons/LoaderButton.kt
chili/src/main/java/com/design2/chili2/view/card/ConfigSelectorCardView.kt
chili/src/main/java/com/design2/chili2/view/card/ConfigToggledCardView.kt
chili/src/main/java/com/design2/chili2/view/card/SingleSelectedCardView.kt
chili/src/main/java/com/design2/chili2/view/card/TitledToggleCardView.kt
chili/src/main/java/com/design2/chili2/view/common/AdditionalDoubleButtonsView.kt
chili/src/main/java/com/design2/chili2/view/common/AdditionalTextView.kt
chili/src/main/java/com/design2/chili2/view/common/AgreementView.kt
chili/src/main/java/com/design2/chili2/view/common/TitledDividerView.kt
chili/src/main/java/com/design2/chili2/view/container/ExpandableCardContainer.kt
chili/src/main/java/com/design2/chili2/view/container/ExpandableContainer.kt

https://jira.devcats.kg/browse/OM-11586

OM-10586 viewBinding for buttons, common and containers

---

chili/src/main/java/com/design2/chili2/view/input/BaseInputView.kt
chili/src/main/java/com/design2/chili2/view/input/MultilineInputView.kt
chili/src/main/java/com/design2/chili2/view/input/UneditableInputView.kt
chili/src/main/java/com/design2/chili2/view/input/otp/OtpInputView.kt
chili/src/main/java/com/design2/chili2/view/modals/base/BaseFragmentBottomSheetDialogFragment.kt
chili/src/main/java/com/design2/chili2/view/modals/base/BaseViewBottomSheetDialogFragment.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/DescriptionBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/DetailedInfoBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/InfoBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/serach_bottom_sheet/SearchSelectorBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/in_app/InAppPushBottomSheet.kt
chili/src/main/java/com/design2/chili2/view/modals/picker/DatePickerDialog.kt
chili/src/main/java/com/design2/chili2/view/modals/picker/RangeDatePickerDialog.kt
chili/src/main/java/com/design2/chili2/view/modals/picker/TimePickerDialog.kt
chili/src/main/java/com/design2/chili2/view/navigation_components/ChiliToolbar.kt
chili/src/main/java/com/design2/chili2/view/navigation_components/StartIconChiliToolbar.kt
chili/src/main/java/com/design2/chili2/view/tooltip/TooltipView.kt
chili/src/main/res-screen/navigation_component/layout/chili_view_toolbar.xml

https://jira.devcats.kg/browse/OM-11642

OM-11642 view binding for input modals and etc

---

app/src/main/java/com/design2/app/adapter/EditableCellViewsAdapter.kt
app/src/main/java/com/design2/app/adapter/SimpleDiscountCardRecyclerViewAdapter.kt
app/src/main/java/com/design2/app/adapter/SimpleTextRecyclerViewAdapter.kt
chili/src/main/java/com/design2/chili2/view/container/grouping_rv/NonShadowGroupVH.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/serach_bottom_sheet/SearchSelectorItemVH.kt
chili/src/main/java/com/design2/chili2/view/snackbar/ChiliSnackBar.kt
chili/src/main/java/com/design2/chili2/view/snackbar/SnackbarLayoutView.kt

https://jira.devcats.kg/browse/OM-11664
https://jira.devcats.kg/browse/OM-11665
https://jira.devcats.kg/browse/OM-11666

OM-11666 OM-11665 OM-11664

---

app/src/main/java/com/design2/app/adapter/EditableCellViewsAdapter.kt
app/src/main/java/com/design2/app/adapter/SimpleDiscountCardRecyclerViewAdapter.kt
app/src/main/java/com/design2/app/adapter/SimpleTextRecyclerViewAdapter.kt
chili/src/main/java/com/design2/chili2/view/cells/BaseCellView.kt
chili/src/main/java/com/design2/chili2/view/cells/ExpandableCellView.kt
chili/src/main/java/com/design2/chili2/view/cells/InfoCellView.kt
chili/src/main/java/com/design2/chili2/view/cells/MultiIconedTitleCellView.kt
chili/src/main/java/com/design2/chili2/view/cells/TitledInfoCellView.kt
chili/src/main/java/com/design2/chili2/view/container/grouping_rv/NonShadowGroupVH.kt
chili/src/main/java/com/design2/chili2/view/input/BaseInputView.kt
chili/src/main/java/com/design2/chili2/view/input/UneditableInputView.kt
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/serach_bottom_sheet/SearchSelectorItemVH.kt
chili/src/main/java/com/design2/chili2/view/modals/picker/DatePickerDialog.kt
chili/src/main/java/com/design2/chili2/view/modals/picker/RangeDatePickerDialog.kt
chili/src/main/java/com/design2/chili2/view/modals/picker/TimePickerDialog.kt

https://jira.devcats.kg/browse/OM-11695

fixed vb naming and access modifiers

---

chili/src/main/java/com/design2/chili2/view/cells/ExpandableCellView.kt
chili/src/main/res-screen/cells_views/layout/chili_view_cell_expandable.xml
chili/src/main/res/drawable-night/chili_ic_chevron_down.xml
chili/src/main/res/drawable/chili_ic_chevron_down.xml

Исправление бага в ExpandableCellView: Корректное изменение начального состояния и обновление иконки chevron
- Исправлен баг в ExpandableCellView, где компонент изначально некорректно изменял своё состояние.
- Обновлена иконка chevron, заменена на то что из фигмы(Дизайн системы).

ExpandableCellView bug fix

---

app/src/main/res/layout/fragment_cell.xml
app/src/main/res/layout/fragment_input_fields.xml
chili/src/main/java/com/design2/chili2/extensions/ViewExtensions.kt
chili/src/main/java/com/design2/chili2/view/cells/AdditionalTextCellView.kt
chili/src/main/java/com/design2/chili2/view/cells/BaseCellView.kt
chili/src/main/java/com/design2/chili2/view/input/otp/OtpInputView.kt
chili/src/main/res/drawable/chili_ripple_bottom_corner_background.xml
chili/src/main/res/drawable/chili_ripple_middle_corner_foreground.xml
chili/src/main/res/drawable/chili_ripple_top_corner_foreground.xml

https://jira.devcats.kg/browse/OM-12404

OM-12404 -> fixed ripple effect in BaseCellView.kt, fixed otp width to 4 cells

---

chili/src/main/java/com/design2/chili2/view/card/IconHolderCardItemView.kt
chili/src/main/res-screen/card_views/layout/chili_view_discount_card.xml

https://www.figma.com/file/KyjN0h7iEG20fjmj7bo57E/Draft_Design-system-Android?type=design&node-id=34-3171&mode=dev

OM-12916_fix_bonus_card_text

---

app/src/main/java/com/design2/app/adapter/SimpleDiscountCardRecyclerViewAdapter.kt
app/src/main/java/com/design2/app/fragments/CardsFragment.kt
chili/src/main/java/com/design2/chili2/view/card/IconHolderCardItemView.kt

https://jira.devcats.kg/browse/OMD-11225

underlay visibility

---

app/src/main/res/layout/activity_toolbar.xml
chili/src/main/res-screen/navigation_component/layout/chili_view_toolbar.xml

Reverts ealmaz/DesignChili2#108

Revert "OM-13299 center toolbar title"

---

chili/src/main/java/com/design2/chili2/extensions/ViewExtensions.kt

Не прогружается штрихкод карты Globus/Народный в экране "Детали карты"

fixed glide listener

---

chili/src/main/java/com/design2/chili2/view/container/HighlighterContainer.kt
chili/src/main/res-screen/buttons/values/button_styles.xml
chili/src/main/res-screen/cells_views/drawable/chili_bg_button_accent.xml
chili/src/main/res/values/colors.xml
chili/src/main/res/values/dimens.xml
chili/src/main/res/values/theme_attributes.xml
chili/src/main/res/values/themes.xml

Some colors and components require for LK Stories

requires components for LK stories

---

app/src/main/java/com/design2/app/fragments/CardsFragment.kt
chili/src/main/java/com/design2/chili2/extensions/ViewExtensions.kt
chili/src/main/java/com/design2/chili2/view/image/AutoScrollCarouselImageView.kt

https://jira.devcats.kg/browse/BONUS-832

pauseAutoScroll is public, listening scrolling with touch events

---

chili/src/main/java/com/design2/chili2/extensions/ViewExtensions.kt
chili/src/main/java/com/design2/chili2/view/image/AutoScrollCarouselImageAdapter.kt
chili/src/main/res/layout/chili_banner_card_view.xml

https://jira.devcats.kg/browse/BONUS-832

fix with wrap and setImageByUrl(width, height)

---

chili/src/main/res/values/themes.xml

https://jira.devcats.kg/browse/OM-28589

 OM-28589 -> changing ChiliToolbar text_size

---

chili/src/main/res/layout/chili_view_card_balance.xml

https://jira.devcats.kg/browse/OM-28612

OM-28612 -> fixing > icon padding

---

chili/src/main/java/com/design2/chili2/view/input/BaseInputView.kt
chili/src/main/res-screen/input_views/layout/chili_view_input_base.xml

https://jira.devcats.kg/browse/OM-28978 --> [android]Инпут суммы в редактировании избранного кликабелен не во всей области

OM-28978_input_small_clickable_area

---

app/src/main/java/com/design2/app/fragments/AllViewsFragment.kt
app/src/main/java/com/design2/app/fragments/DividerFragment.kt
app/src/main/res/layout/fragment_all_views.xml
app/src/main/res/layout/fragment_divider.xml
chili3/src/main/java/kg/devcats/chili3/view/divider/DividerView.kt
chili3/src/main/res/drawable/chili_ic_notification.xml
chili3/src/main/res/layout/chili_view_divider.xml
chili3/src/main/res/values/attrs.xml
chili3/src/main/res/values/text-styles.xml
chili3/src/main/res/values/themes.xml

https://jira.devcats.kg/browse/ALGA-742

ALGA-742_divider_view -> DividerView

---

chili3/src/main/res/values-night/themes.xml
chili3/src/main/res/values/colors.xml
chili3/src/main/res/values/theme_attributes.xml
chili3/src/main/res/values/themes.xml

https://jira.devcats.kg/browse/ALGA-748 --> Добавить новые цвета в чили3

Alga 748 add new colors to chili 3

---

chili/src/main/java/com/design2/chili2/view/buttons/IconedButton.kt
chili/src/main/res-screen/buttons/layout/chili_view_button_iconed.xml
chili/src/main/res/values/attrs.xml

https://jira.devcats.kg/browse/ALGA-729 --> В рамках этой задачи добавил startIcon компоненту IconedButton в chili2

ALGA-729_within_scope_this_add_start_icon_to_iconed_button

---

app/src/main/java/com/design2/app/fragments/CardsFragment.kt
app/src/main/res/layout/fragment_cards.xml
chili/src/main/java/com/design2/chili2/extensions/GlideExtension.kt
chili/src/main/java/com/design2/chili2/view/common/AnimatedProgressLine.kt
chili/src/main/res-screen/cells_views/values/cell_view_styles.xml
chili/src/main/res/values/attrs.xml
chili3/src/main/java/kg/devcats/chili3/util/AttributesEnums.kt
chili3/src/main/java/kg/devcats/chili3/view/card/MyConnectionCardView.kt
chili3/src/main/java/kg/devcats/chili3/view/cells/PackageLeftoverHorizontalView.kt
chili3/src/main/res-screen/card_views/layout/chili_view_my_connection_unauthorized.xml
chili3/src/main/res-screen/card_views/values/card_view_styles.xml
chili3/src/main/res/layout/chili_view_my_connection_card_view.xml
chili3/src/main/res/layout/chili_view_package_leftover_horizontal_view.xml
chili3/src/main/res/values/attrs.xml
chili3/src/main/res/values/colors.xml

https://jira.o.kg/browse/LKAPP-4805

Lkapp 4805 my connection card view

---

chili3/src/main/java/kg/devcats/chili3/view/card/MyConnectionCardView.kt
chili3/src/main/java/kg/devcats/chili3/view/cells/PackageLeftoverHorizontalView.kt
chili3/src/main/res-screen/card_views/layout/chili_view_my_connection_unauthorized.xml
chili3/src/main/res/layout/chili_view_my_connection_card_view.xml
chili3/src/main/res/layout/chili_view_package_leftover_horizontal_view.xml

https://jira.o.kg/browse/LKAPP-4869

LKAPP-4869_MyConnectionCardView -> My connection card view fixes

---

chili3/src/main/res/layout/chili_view_card_product_banner.xml

https://jira.devcats.kg/browse/ALGA-1374

ALGA-1374 -> centered title of ProductBannerCardView

---

chili3/src/main/java/kg/devcats/chili3/view/container/BottomSheetWithRecycler.kt

https://jira.devcats.kg/browse/ALGA-1505

ALGA-1505 -> added setBottomPadding to BottomSheetWithRecycler

---

chili3/src/main/java/kg/devcats/chili3/view/cells/CardCellView.kt
chili3/src/main/res/layout/chili_view_card_cell.xml

https://jira.devcats.kg/browse/ALGA-1931

ALGA-1931 -> added logic to remove bottom constraint in CardCellView

---

chili/src/main/java/com/design2/chili2/view/cells/BaseCellView.kt

jira task - https://jira.o.kg/browse/DOM-2653

added new method

---

app/src/main/java/com/design2/app/fragments/BottomSheetsFragment.kt
app/src/main/res/layout/frgment_bottom_sheets.xml
chili/src/main/java/com/design2/chili2/view/modals/bottom_sheet/DetailedDescriptionBottomSheet.kt
chili/src/main/res/layout/chili_detailed_desc_bottom_sheet.xml

- added new bottom sheet with more information

OM-30545 -> added new bottom sheet

---

app/src/main/java/com/design2/app/fragments/CardsFragment.kt
app/src/main/res/layout/fragment_cards.xml
chili3/src/main/java/kg/devcats/chili3/view/card/ProductCardView.kt
chili3/src/main/res-screen/card_views/layout/chili_view_card_product.xml
chili3/src/main/res/values/attrs.xml
chili3/src/main/res/values/theme_attributes.xml
chili3/src/main/res/values/themes.xml

Task: https://jira.devcats.kg/browse/OM-30595

OM-30595(refactor): Added discount icon for ProductCardView

---

app/src/main/java/com/design2/app/fragments/CardsFragment.kt
app/src/main/res/layout/fragment_cards.xml
chili3/src/main/java/kg/devcats/chili3/view/card/CardHorizontalDivider.kt
chili3/src/main/res-screen/card_views/values/card_view_styles.xml
chili3/src/main/res/drawable/chili_bg_card_horizontal_divider.xml
chili3/src/main/res/layout/chili_view_card_horizontal_divider.xml
chili3/src/main/res/values-night/themes.xml
chili3/src/main/res/values/attrs.xml
chili3/src/main/res/values/theme_attributes.xml
chili3/src/main/res/values/themes.xml

Task: https://jira.devcats.kg/browse/OM-30652

OM-30652(feature): Added new horizontal card divider

---

chili/src/main/java/com/design2/chili2/view/card/ExpandableCardItemView.kt
chili/src/main/res/values/attrs.xml

setTitleColor for expandedCardItem

added property for ExpandableCardItemView

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/design2/app/ToolbarActivity.kt
app/src/main/java/com/design2/app/activities/CollapsingToolbarActivity.kt
app/src/main/res/layout/activity_collapsing_toolbar.xml
app/src/main/res/layout/activity_toolbar.xml
chili/src/main/res/values/attrs.xml
chili3/src/main/java/kg/devcats/chili3/view/toolbar/CollapsingChiliToolbar.kt
chili3/src/main/res/layout/chili_view_collapsing_toolbar.xml

https://jira.devcats.kg/browse/OM-32407

Om 32407 new
